### ISSUE TITLE
Unable to import izip from intertools

### ISSUE THREAD

**Issue by Osmanila** [insidesherpa/JPMC-tech-task-1#10]
I have already set up the environment with cmd and git bash(app), but I couldn't run the server.py file. first issue was missing parenthesis which I fix it and the second one is unable to import izip from intertools.
I attached the screenshots. Thank you
![1](https://user-images.githubusercontent.com/52209263/67316240-142a3580-f4d6-11e9-9c3e-88c318f9ce5b.png)
![2](https://user-images.githubusercontent.com/52209263/67316435-69664700-f4d6-11e9-90f9-77903e4b4a41.jpg)

**Comment by jbf-insidesherpa** [comment]
@Osmanila what's your Python version? I think you're using 3+ ? The instructions say you have to use versions in the 2.7.x domain. Let me know how that goes for you.

**Comment by Osmanila** [comment]
Thank you so much, I have installed python 3+ previously and though works well with the latest version. I removed the 3+ and installed 2.7 it works.

**Comment by jbf-insidesherpa** [comment]
No worries @Osmanila. You can keep both python3+ and python2.7.x in your machine. You just have to  make it explicit in your path what  the command`python` points to e.ou can have `python` mapped to python2.7.x and `python3` mapped to python3.y 

As a side note we're uploading a python3 version of the code here soon.
