### ISSUE TITLE
Indent errors

### ISSUE THREAD

**Issue by mcendrd** [insidesherpa/JPMC-tech-task-1#11]
Everytime I try to alter the code under getRatio I get indentation errors. I've checked and rechecked and have no clue what I'm doing wrong.  See screen shot.
![10-22-2019 3-24-04 PM](https://user-images.githubusercontent.com/56895312/67330007-4d1bd780-f4e1-11e9-84d6-4c2e4866124a.jpg)

**Comment by jbf-insidesherpa** [comment]
@mcendrd can you share the link to your forked REPL? Thanks!

**Comment by jbf-insidesherpa** [comment]
@mcendrd https://repl.it/talk/ask/Python-spacing-and-tab-issue/9425

My advice is when you make changes (at least for the current REPL), remove all previous comments and start from the `def <function_name>:` line and hit enter, then add your changes step by step following the right indentation. It should work properly. I'll include a gif / screencast so you can understand how to do it. 

![Peek 2019-10-23 15-27](https://user-images.githubusercontent.com/54832297/67443643-30de7e80-f638-11e9-8d59-8c7f35b4f782.gif)

PS - We're working on seeing if we can eliminate this issue in REPL. As a related note, we're uploading a python3 version soon so if you're more comfortable with that it should be available soon (see Pull Requests in this repo)
