### ISSUE TITLE
Server.py Tech-task2

### ISSUE THREAD

**Issue by jmoyalan6266** [insidesherpa/JPMC-tech-task-1#14]
There is no server.py file in the Tech task 2 folder.

**Comment by jbf-insidesherpa** [comment]
@jmoyalan6266 this issues thread is for tech task 1. For tech task 2 you submit your issues at https://github.com/insidesherpa/JPMC-tech-task-2/issues.

And to answer your question, the server.py in tech task 2 is in the datafeed folder
