### ISSUE TITLE
Issue creating a Patch File

### ISSUE THREAD

**Issue by bertram9** [insidesherpa/JPMC-tech-task-1#16]
Hello Support,

My name is Bertram and i am currently in your insidesherpa  JP Morgan  Virtual Internship Software Engineering program  and i am currently having issue with creating a patch file as the last task for module 1. I tried following all the steps to create one but i kept receiving the following error. runner@a302c561e5f6:~$ /jpm_module_1
bash: /jpm_module_1: No such file or directory
 Please can you be of assistance in explaining to me me where i went wrong?

**Comment by jbf-insidesherpa** [comment]
@bertram9 I believe we've resolved this already on your end right? I'm closing this issue now.
