### ISSUE TITLE
indentationError

### ISSUE THREAD

**Issue by jo9090** [insidesherpa/JPMC-tech-task-1#17]
for quote in quotes:

**is giving me indentation error**

indentationerror: unindent does not match any outer indetation level

**Comment by jbf-insidesherpa** [comment]
@jo9090 I'm assuming you're probably doing the REPL version?
If so there were workarounds discussed in the REPL guide: https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/repl_mod1_v4a.pdf

Please follow the workarounds there for the indentation issue. My suggestion would be to use workaround2. There's even an example gif that shows how to do it: (page13/45) https://drive.google.com/file/d/1IIT_vN56BltztJMdi9ccPFiqk6LrIqus/view

Let me know how it goes on your end
