### ISSUE TITLE
Error message when I try to run "python client.py" 

### ISSUE THREAD

**Issue by bentoks2016** [insidesherpa/JPMC-tech-task-1#18]
I get the following error messages when I try to run "python client.py" 

Please see attached screenshot

![Screen Shot 2019-11-10 at 1 04 40 PM](https://user-images.githubusercontent.com/24797112/68548436-e17baa80-03ba-11ea-8970-977ac95131db.png)

**Comment by jbf-insidesherpa** [comment]
@bentoks2016 you need to be running the server application alongside the client application for everything to work.

Starting client.py via `python client.py` when you haven't even started the server will throw that kind of error.

Make sure to start the server first in a separate terminal. Open another terminal in the same repository/directory and run `python server.py`

**Comment by attmesh** [comment]
When trying to open the server first it says. 
Traceback (most recent call last):
  File "server.py", line 26, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser

So, client.py cannot be opened still.

**Comment by jbf-insidesherpa** [comment]
@attmesh the setup instructions discusses how you can solve that issue.
You need to install the dependency using `pip` (python's package manager)
Depending on your system your on mac/linux/win, the instructions tell you how to do it

**Comment by attmesh** [comment]
Yes, I did install the dateutil running it on my terminal as I use linux.
But still it's showing up the same kind of errors with the code. Not
compiling.

**Comment by jbf-insidesherpa** [comment]
@attmesh check your version of `pip`. Make sure it maps to the version of python you're using
See my example:

![image](https://user-images.githubusercontent.com/54832297/68994690-ef509480-08c0-11ea-8dd4-4931800c3b20.png)

**Comment by Primo007** [comment]
I have a similar problem, I followed all instructions but my error seems to be from when importing from "client3" which was copied to new_client. Please any help will be very much appreciated.

![Capture](https://user-images.githubusercontent.com/57997978/69293433-21d3f780-0c09-11ea-9442-32d460a66a77.PNG)

**Comment by jbf-insidesherpa** [comment]
@Primo007 what REPL environment are you using? And what changes did you make? Perhaps you can share your REPL environment link? You can do it via the share button. Or, better, if you have a REPL account, you can share it via the invite button after you've forked from the original REPL link

**Comment by Primo007** [comment]
Hi, Thank you for reaching out. Kindly shear your username?

**Comment by jbf-insidesherpa** [comment]
@Primo007 you can invite "joe@insidesherpa.com" via the invite button

**Comment by Primo007** [comment]
Great,
Thanks

**Comment by raghav4** [comment]
I'm facing the same issue, can anyone please help me out with this?
```bash
raceback (most recent call last):
  File "server.py", line 26, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser
```

I've pip version `pip 20.0.2 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)`
My python version `Python 2.7.17`
