### ISSUE TITLE
Unable to resolve KEY ERROR: 'DEF'

### ISSUE THREAD

**Issue by UTKyle** [insidesherpa/JPMC-tech-task-1#24]
I have tried re-typing this line multiple times but I am unable to resolve the error below. I have exported my files and attached as a zip. 
Thank you!

HTTP server started on port 8080
Quoted ABC at (bid:118.13, ask:116.63, price:117.38)
Traceback (most recent call last):
  File "client.py", line 41, in <module>
    print "Ratio %s" % getRatio(prices['ABC'], prices['DEF'])
KeyError: 'DEF'

[FairUnripeAcrobat.zip](https://github.com/insidesherpa/JPMC-tech-task-1/files/3882937/FairUnripeAcrobat.zip)

**Comment by jbf-insidesherpa** [comment]
@UTKyle same issue here: https://github.com/insidesherpa/JPMC-tech-task-1/issues/22#issuecomment-557395715

please just follow the thread/suggestion...

**Comment by UTKyle** [comment]
Thank you! The referenced issue fixed my problem.
