### ISSUE TITLE
Test case is missing

### ISSUE THREAD

**Issue by januslinhc** [insidesherpa/JPMC-tech-task-1#5]
```
Acceptance Criteria

getRatio function should return the ratio of the two stock prices
getDataPoint function should return correct tuple of stock name, bid_price, ask_price and price. Note: price of a stock = average of bid and ask
All unit tests inside client_tests.py have to pass
Add more unit tests to cover other edge cases
Upload a git patch file as the submission to this task
```

May I know is that the sample test cases are missing?

**Comment by jbf-insidesherpa** [comment]
@januslinhc not sure I understand your question properly. If this is regarding the unit tests, all the unit tests are located in the client_test.py file.

There are two tests there that have been initially defined i.e. `test_getDataPoint_calculatePrice` and `test_getDataPoint_calculatePriceBidGreaterThanAsk`. You'll need to add assertions for them to be completed, i.e. use the getDataPoint function (which you've hopefully corrected / modified to get the right stock price calculation) and then make assertions. Of course it would be also great if you can add more unit tests to cover the rest of the application e.g. unit test to help us check `getRatio` works correctly, etc.
